# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_business', models.DateTimeField()),
                ('store_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('check_number', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('order_mode_id', models.IntegerField()),
                ('day_part_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('disc_price', models.FloatField()),
                ('quick_combo_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Store_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('region', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('store_name', models.CharField(max_length=128)),
                ('opening_date', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S')),
                ('regional_manager', models.CharField(max_length=128)),
                ('area_lead', models.CharField(max_length=128)),
                ('is_open', models.IntegerField()),
                ('is_DT', models.IntegerField()),
                ('is_DL', models.IntegerField()),
                ('store_format', models.CharField(max_length=128)),
                ('bk_store_id', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('store_short_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'store_details',
            },
        ),
    ]
